server:
  port: 8082

spring:
  application:
    name: email-service

  kafka:
    bootstrap-servers: localhost:9092

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.nds: DEBUG
    org.springframework.kafka: INFO
