apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-service
  namespace: notification-system
  labels:
    app: push-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: push-service
  template:
    metadata:
      labels:
        app: push-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8084"
    spec:
      containers:
        - name: push-service
          image: nds/push-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: nds-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: nds-config
                  key: KAFKA_BOOTSTRAP_SERVERS
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
